#!/bin/sh
 
mount -t proc none /proc
mount -t sysfs none /sys

#Create device nodes
mknod /dev/null c 1 3
mknod /dev/tty c 5 0
mdev -s
 
echo -e "\nBoot took $(cut -d' ' -f1 /proc/uptime) seconds\n"
mount -t 9p -o trans=virtio,version=9p2000.L host0 /share

echo '7 7 7 7' > /proc/sys/kernel/printk
 
exec /bin/sh
