# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_SAMPLE_RUST_MINIMAL)		+= rust_minimal.o
obj-$(CONFIG_SAMPLE_RUST_PRINT)			+= rust_print.o
obj-$(CONFIG_SAMPLE_RUST_FS)			+= rust_fs.o
obj-$(CONFIG_SAMPLE_RUST_LDD02)			+= rust_ldd02.o
obj-$(CONFIG_SAMPLE_RUST_LDD03)			+= rust_ldd03.o
obj-$(CONFIG_SAMPLE_RUST_LDD04)			+= rust_ldd04.o
obj-$(CONFIG_SAMPLE_RUST_LDD05)			+= rust_ldd05.o

subdir-$(CONFIG_SAMPLE_RUST_HOSTPROGS)		+= hostprogs
